config/routes.rb
Rails.application.routes.draw do
  root "gardens#index"
  resources :gardens, except: :index do
    resources :plants, only: :create
  end
  resources :plants, only: :destroy do
    resources :plant_tags, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true

  has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :plant_tags, dependent: :destroy
  has_many :tags, through: :plant_tags

  validates :name, :image_url, presence: true
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant
  belongs_to :tag

  validates :tag, uniqueness: {scope: :plant, message: "already added"}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :plant_tags, dependent: :destroy
  has_many :plants, through: :plant_tags

  validates :name, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[ show edit update destroy ]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)
    if @garden.save
      redirect_to @garden, notice: "Garden was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: "Garden was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: "Garden was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
  def new
    @plant_tag = PlantTag.new
    @plant = Plant.find(params[:plant_id])
  end

  def create
    @plant = Plant.find(params[:plant_id])
    @tags = Tag.where(id: params[:plant_tag][:tag])
    @tags.each do |tag|
      plant_tag = PlantTag.new(plant: @plant, tag: tag)
      unless plant_tag.save
        @plant_tag = PlantTag.new
        render :new, status: :unprocessable_entity
        return
        # redirect_to new_plant_plant_tag_path(@plant), alert: plant_tag.errors.messages
      end
    end
    redirect_to garden_path(@plant.garden)
    # if @plant_tag.save
    #   redirect_to garden_path(@plant.garden)
    # else
    #   render :new, status: :unprocessable_entity
    # end
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    # Find the garden
    @garden = Garden.find(params[:garden_id])
    # Create the plant with (strong) params of the form
    @plant = Plant.new(plant_params)
    # Assign garden to the plant
    @plant.garden = @garden
    # Save the plant
      # If save redirect to garden show
    if @plant.save
      redirect_to garden_path(@garden)
    # Else, re-render the form
    else
      # redirect_to garden_path(@garden)
      render "gardens/show", status: :unprocessable_entity
    end
  end

  def destroy
    # Find the plant
    @plant = Plant.find(params[:id])
    # Destroy the plant
    @plant.destroy
    # Redirect to garden show
    redirect_to garden_path(@plant.garden), status: :see_other
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/_garden.html.erb
<div id="<%= dom_id garden %>">
  <p>
    <strong>Name:</strong>
    <%= garden.name %>
  </p>

  <p>
    <strong>Banner url:</strong>
    <%= garden.banner_url %>
  </p>

</div>

app/views/gardens/edit.html.erb
<h1>Editing garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Show this garden", @garden %> |
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Gardens</h1>

  <div id="gardens">
    <% @gardens.each do |garden| %>
      <%= render garden %>
      <p>
        <%= link_to "Show this garden", garden %>
      </p>
    <% end %>
  </div>

  <%= link_to "New garden", new_garden_path %>
</div>


<%# Faire le schéma de DB %>
<%# Générer le model Tag %>
<%# Générer le model de la table de jointure PlantTag %>
<%# Ajouter des validations et associations %>
<%# Tester dans rails c %>

app/views/gardens/new.html.erb
<h1>New garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">
  <div class="container">
    <h1 class="text-center"><%= @garden.name %></h1>
  </div>
</div>

<div class="container">
  <div class="row mt-5">
    <% @garden.plants.each do |plant| %>
      <div class="col-4">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image_url%>)">
          <%= plant.name %>
          <%= link_to "+", plant_path(plant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "card-remove-link" %>
          <div class="card-tags">
            <% plant.tags.each do |tag| %>
              <span><%= tag.name %></span>
            <% end %>
            <%= link_to "+", new_plant_plant_tag_path(plant) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center my-5">
    <div class="col-4">
      <h4>Add a plant: </h4>
      <%= simple_form_for [@garden, @plant] do |f| %>
        <%= f.input :name, placeholder: "Palm tree" %>
        <%= f.input :image_url, placeholder: "Your image url" %>
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant_tags/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h1>Add new tag for <%= @plant.name %></h1>

      <%= simple_form_for [@plant, @plant_tag] do |f| %>
        <%= f.input :tag, collection: Tag.all, input_html: {multiple: true, data: {controller: "tom-select"}}, include_hidden: false %>
        <%# # <%= f.association :tag, input_html: {multiple: true, data: {controller: "tom-select"}} %>
        <%= f.submit "Add tag", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>